apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
        - image: ubuntu:20.04
          imagePullPolicy: IfNotPresent
          name: ubuntu
          args:
            - /bin/sh
            - -c 
            - | 
              sleep 86400d

          volumeMounts:
            - mountPath: /data
              name: data
            
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: efs-claim

